CREATE TABLE IF NOT EXISTS gm_edge_policy (
    id                                      VARCHAR(64)   PRIMARY KEY,
    enabled                                 BOOLEAN       NOT NULL DEFAULT FALSE,
    inbound_enabled                         BOOLEAN       NOT NULL DEFAULT TRUE,
    inbound_bind_address                    VARCHAR(128)  NOT NULL DEFAULT '0.0.0.0',
    inbound_starttls_port                   INTEGER       NOT NULL DEFAULT 2525,
    inbound_implicit_tls_port               INTEGER       NOT NULL DEFAULT 2465,
    inbound_backlog                         INTEGER       NOT NULL DEFAULT 128,
    inbound_max_connections                 INTEGER       NOT NULL DEFAULT 1024,
    outbound_enabled                        BOOLEAN       NOT NULL DEFAULT TRUE,
    outbound_bind_address                   VARCHAR(128)  NOT NULL DEFAULT '127.0.0.1',
    outbound_smart_host_port                INTEGER       NOT NULL DEFAULT 2526,
    outbound_backlog                        INTEGER       NOT NULL DEFAULT 128,
    outbound_max_connections                INTEGER       NOT NULL DEFAULT 512,
    postfix_host                            VARCHAR(254)  NOT NULL DEFAULT '127.0.0.1',
    postfix_port                            INTEGER       NOT NULL DEFAULT 2530,
    tls_protocols                           VARCHAR(512)  NOT NULL DEFAULT 'TLCPv1.1,TLCP,TLSv1.3',
    tls_cipher_suites                       VARCHAR(2048) NOT NULL DEFAULT 'TLS_SM4_GCM_SM3,TLS_SM4_CCM_SM3',
    tls_key_store_path                      VARCHAR(1024),
    tls_key_store_password_secret_ref       VARCHAR(1024),
    tls_key_store_type                      VARCHAR(32)   NOT NULL DEFAULT 'PKCS12',
    tls_trust_store_path                    VARCHAR(1024),
    tls_trust_store_password_secret_ref     VARCHAR(1024),
    tls_trust_store_type                    VARCHAR(32)   NOT NULL DEFAULT 'PKCS12',
    tls_trust_all                           BOOLEAN       NOT NULL DEFAULT FALSE,
    connect_timeout_ms                      INTEGER       NOT NULL DEFAULT 10000,
    read_timeout_ms                         INTEGER       NOT NULL DEFAULT 60000,
    max_message_size_bytes                  INTEGER       NOT NULL DEFAULT 52428800,
    max_line_length_bytes                   INTEGER       NOT NULL DEFAULT 16384,
    max_recipients                          INTEGER       NOT NULL DEFAULT 100,
    routes_json                             TEXT          NOT NULL DEFAULT '[]',
    created_at                              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at                              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version                                 BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT chk_gm_edge_inbound_starttls_port CHECK (inbound_starttls_port BETWEEN 1 AND 65535),
    CONSTRAINT chk_gm_edge_inbound_implicit_tls_port CHECK (inbound_implicit_tls_port BETWEEN 1 AND 65535),
    CONSTRAINT chk_gm_edge_outbound_smart_host_port CHECK (outbound_smart_host_port BETWEEN 1 AND 65535),
    CONSTRAINT chk_gm_edge_postfix_port CHECK (postfix_port BETWEEN 1 AND 65535),
    CONSTRAINT chk_gm_edge_inbound_listener_ports CHECK (inbound_starttls_port <> inbound_implicit_tls_port),
    CONSTRAINT chk_gm_edge_inbound_backlog CHECK (inbound_backlog > 0),
    CONSTRAINT chk_gm_edge_outbound_backlog CHECK (outbound_backlog > 0),
    CONSTRAINT chk_gm_edge_inbound_max_connections CHECK (inbound_max_connections > 0),
    CONSTRAINT chk_gm_edge_outbound_max_connections CHECK (outbound_max_connections > 0),
    CONSTRAINT chk_gm_edge_connect_timeout CHECK (connect_timeout_ms > 0),
    CONSTRAINT chk_gm_edge_read_timeout CHECK (read_timeout_ms > 0),
    CONSTRAINT chk_gm_edge_message_size CHECK (max_message_size_bytes > 0),
    CONSTRAINT chk_gm_edge_line_length CHECK (max_line_length_bytes > 0),
    CONSTRAINT chk_gm_edge_max_recipients CHECK (max_recipients > 0)
);
